77Annex-MVC5_v1.0.0 22 08/Annex-MVC5_v1.0.0 22 08/Admin/Vertical/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vertical.Controllers
{
    public class FormController : Controller
    {
        [ActionName("form-advanced")]
        public ActionResult formadvanced()
        {
            return View();
        }

        [ActionName("form-editors")]
        public ActionResult formeditors()
        {
            return View();
        }

        [ActionName("form-elements")]
        public ActionResult formelements()
        {
            return View();
        }

        [ActionName("form-mask")]
        public ActionResult formmask()
        {
            return View();
        }

        [ActionName("form-summernote")]
        public ActionResult formsummernote()
        {
            return View();
        }

        [ActionName("form-uploads")]
        public ActionResult formuploads()
        {
            return View();
        }

        [ActionName("form-validation")]
        public ActionResult formvalidation()
        {
            return View();
        }

        [ActionName("form-xeditable")]
        public ActionResult formxeditable()
        {
            return View();
        }
    }
}

77Annex-MVC5_v1.0.0 22 08/Annex-MVC5_v1.0.0 22 08/Admin/Vertical/Controllers/IconsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vertical.Controllers
{
    public class IconsController : Controller
    {
        [ActionName("icons-dripicons")]
        public ActionResult iconsdripicons()
        {
            return View();
        }
        [ActionName("icons-fontawesome")]
        public ActionResult iconsfontawesome()
        {
            return View();
        }
        [ActionName("icons-ion")]
        public ActionResult iconsion()
        {
            return View();
        }
        [ActionName("icons-material")]
        public ActionResult iconsmaterial()
        {
            return View();
        }
        [ActionName("icons-themify")]
        public ActionResult iconsthemify()
        {
            return View();
        }
        [ActionName("icons-typicons")]
        public ActionResult iconstypicons()
        {
            return View();
        }
    }
}

77Annex-MVC5_v1.0.0 22 08/Annex-MVC5_v1.0.0 22 08/Admin/Vertical/Controllers/MapsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vertical.Controllers
{
    public class MapsController : Controller
    {
        [ActionName("maps-google")]
        public ActionResult mapsgoogle()
        {
            return View();
        }
        [ActionName("maps-vector")]
        public ActionResult mapsvector()
        {
            return View();
        }
    }
}

77Annex-MVC5_v1.0.0 22 08/Annex-MVC5_v1.0.0 22 08/Admin/Vertical/Controllers/UIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vertical.Controllers
{
    public class UIController : Controller
    {
        [ActionName("ui-buttons")]
        public ActionResult uibuttons()
        {
            return View();
        }
        [ActionName("ui-cards")]
        public ActionResult uicards()
        {
            return View();
        }
        [ActionName("ui-tabs-accordions")]
        public ActionResult uitabsaccordions()
        {
            return View();
        }
        [ActionName("ui-modals")]
        public ActionResult uimodals()
        {
            return View();
        }
        [ActionName("ui-images")]
        public ActionResult uiimages()
        {
            return View();
        }
        [ActionName("ui-alerts")]
        public ActionResult uialerts()
        {
            return View();
        }
        [ActionName("ui-progressbars")]
        public ActionResult uiprogressbars()
        {
            return View();
        }
        [ActionName("ui-dropdowns")]
        public ActionResult uidropdowns()
        {
            return View();
        }
        [ActionName("ui-lightbox")]
        public ActionResult uilightbox()
        {
            return View();
        }
        [ActionName("ui-navs")]
        public ActionResult uinavs()
        {
            return View();
        }
        [ActionName("ui-pagination")]
        public ActionResult uipagination()
        {
            return View();
        }
        [ActionName("ui-popover-tooltips")]
        public ActionResult uipopovertooltips()
        {
            return View();
        }
        [ActionName("ui-badge")]
        public ActionResult uibadge()
        {
            return View();
        }
        [ActionName("ui-carousel")]
        public ActionResult uicarousel()
        {
            return View();
        }
        [ActionName("ui-video")]
        public ActionResult uivideo()
        {
            return View();
        }
        [ActionName("ui-typography")]
        public ActionResult uitypography()
        {
            return View();
        }
        [ActionName("ui-sweet-alert")]
        public ActionResult uisweetalert()
        {
            return View();
        }
        [ActionName("ui-grid")]
        public ActionResult uigrid()
        {
            return View();
        }
    }
}

77Annex-MVC5_v1.0.0 22 08/Annex-MVC5_v1.0.0 22 08/Admin/Vertical/Views/Shared/_Footer.cshtml
<footer class="footer">    
    © @DateTime.Now.Year Annex by Mannatthemes.
</footer>

77Annex-MVC5_v1.0.0 22 08/Annex-MVC5_v1.0.0 22 08/Admin/Vertical/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Annex - Responsive Bootstrap 4 Admin Dashboard</title>
    <meta content="Admin Dashboard" name="description" />
    <meta content="Mannatthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="shortcut icon" href="~/assets/images/favicon.ico">    


</head>

<body class="fixed-left">

    <!-- Loader -->
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>

    <!-- Begin page -->
    <div id="wrapper">

        <!-- ========== Left Sidebar Start ========== -->
        @Html.Partial("_LeftSideBar")
        <!-- Left Sidebar End -->
        <!-- Start right Content here -->

        <div class="content-page">
            <!-- Start content -->
            <div class="content">

                <!-- Top Bar Start -->
                @Html.Partial("_TopBar")
                <!-- Top Bar End -->

                <div class="page-content-wrapper ">
                    @RenderBody()
                    @Styles.Render("~/Content/css")
                </div> <!-- Page content Wrapper -->

            </div> <!-- content -->

            @Html.Partial("_Footer")

        </div>
        <!-- End Right content here -->

    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

77Annex-MVC5_v1.0.0 22 08/Annex-MVC5_v1.0.0 22 08/Admin/Vertical/Views/Shared/_LeftSideBar.cshtml
<div class="left side-menu">
    <button type="button" class="button-menu-mobile button-menu-mobile-topbar open-left waves-effect">
        <i class="ion-close"></i>
    </button>

    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="@Url.Action("Index", "Dashboard")" class="logo"><i class="mdi mdi-assistant"></i> Annex</a>
        </div>
    </div>

    <div class="sidebar-inner slimscrollleft">

        <div id="sidebar-menu">
            <ul>
                <li class="menu-title">Main</li>

                <li>
                    <a href="@Url.Action("Index", "Dashboard")" class="waves-effect">
                        <i class="mdi mdi-airplay"></i>
                        <span> Dashboard <span class="badge badge-pill badge-primary float-right">7</span></span>
                    </a>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-layers"></i> <span> Advanced UI </span> <span class="float-right"><i class="mdi mdi-chevron-right"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("advanced-highlight", "Advanced")">Highlight</a></li>
                        <li><a href="@Url.Action("advanced-rating", "Advanced")">Rating</a></li>
                        <li><a href="@Url.Action("advanced-alertify", "Advanced")">Alertify</a></li>
                        <li><a href="@Url.Action("advanced-rangeslider", "Advanced")">Range Slider</a></li>
                    </ul>
                </li>

                <li>
                    <a href="@Url.Action("calendar", "Dashboard")" class="waves-effect"><i class="mdi mdi-calendar-clock"></i><span> Calendar </span></a>
                </li>

                <li class="menu-title">Components</li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-bullseye"></i> <span> UI Elements </span> <span class="float-right"><i class="mdi mdi-chevron-right"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("ui-buttons", "UI")">Buttons</a></li>
                        <li><a href="@Url.Action("ui-cards", "UI")">Cards</a></li>
                        <li><a href="@Url.Action("ui-tabs-accordions", "UI")">Tabs &amp; Accordions</a></li>
                        <li><a href="@Url.Action("ui-modals", "UI")">Modals</a></li>
                        <li><a href="@Url.Action("ui-images", "UI")">Images</a></li>
                        <li><a href="@Url.Action("ui-alerts", "UI")">Alerts</a></li>
                        <li><a href="@Url.Action("ui-progressbars", "UI")">Progress Bars</a></li>
                        <li><a href="@Url.Action("ui-dropdowns", "UI")">Dropdowns</a></li>
                        <li><a href="@Url.Action("ui-lightbox", "UI")">Lightbox</a></li>
                        <li><a href="@Url.Action("ui-navs", "UI")">Navs</a></li>
                        <li><a href="@Url.Action("ui-pagination", "UI")">Pagination</a></li>
                        <li><a href="@Url.Action("ui-popover-tooltips", "UI")">Popover & Tooltips</a></li>
                        <li><a href="@Url.Action("ui-badge", "UI")">Badge</a></li>
                        <li><a href="@Url.Action("ui-carousel", "UI")">Carousel</a></li>
                        <li><a href="@Url.Action("ui-video", "UI")">Video</a></li>
                        <li><a href="@Url.Action("ui-typography", "UI")">Typography</a></li>
                        <li><a href="@Url.Action("ui-sweet-alert", "UI")">Sweet-Alert</a></li>
                        <li><a href="@Url.Action("ui-grid", "UI")">Grid</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-clipboard-outline"></i><span> Forms </span> <span class="badge badge-pill badge-info float-right">8</span></a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("form-elements", "Form")">Form Elements</a></li>
                        <li><a href="@Url.Action("form-validation", "Form")">Form Validation</a></li>
                        <li><a href="@Url.Action("form-advanced", "Form")">Form Advanced</a></li>
                        <li><a href="@Url.Action("form-editors", "Form")">Form Editors</a></li>
                        <li><a href="@Url.Action("form-uploads", "Form")">Form File Upload</a></li>
                        <li><a href="@Url.Action("form-mask", "Form")">Form Mask</a></li>
                        <li><a href="@Url.Action("form-summernote", "Form")">Summernote</a></li>
                        <li><a href="@Url.Action("form-xeditable", "Form")">Form Xeditable</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-gauge"></i><span> Charts </span> <span class="float-right"><i class="mdi mdi-chevron-right"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("charts-morris", "Charts")">Morris Chart</a></li>
                        <li><a href="@Url.Action("charts-chartist", "Charts")">Chartist Chart</a></li>
                        <li><a href="@Url.Action("charts-chartjs", "Charts")">Chartjs Chart</a></li>
                        <li><a href="@Url.Action("charts-flot", "Charts")">Flot Chart</a></li>
                        <li><a href="@Url.Action("charts-c3", "Charts")">C3 Chart</a></li>
                        <li><a href="@Url.Action("charts-other", "Charts")">Jquery Knob Chart</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-cards-outline"></i> <span> Icons </span> <span class="float-right"><i class="mdi mdi-chevron-right"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("icons-material", "Icons")">Material Design</a></li>
                        <li><a href="@Url.Action("icons-ion", "Icons")">Ion Icons</a></li>
                        <li><a href="@Url.Action("icons-fontawesome", "Icons")">Font Awesome</a></li>
                        <li><a href="@Url.Action("icons-themify", "Icons")">Themify Icons</a></li>
                        <li><a href="@Url.Action("icons-dripicons", "Icons")">Dripicons</a></li>
                        <li><a href="@Url.Action("icons-typicons", "Icons")">Typicons Icons</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-table"></i><span> Tables </span> <span class="float-right"><i class="mdi mdi-chevron-right"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("tables-basic", "Tables")">Basic Tables</a></li>
                        <li><a href="@Url.Action("tables-datatable", "Tables")">Data Table</a></li>
                        <li><a href="@Url.Action("tables-responsive", "Tables")">Responsive Table</a></li>
                        <li><a href="@Url.Action("tables-editable", "Tables")">Editable Table</a></li>
                    </ul>
                </li>

                <li class="menu-title">Extra</li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-map-marker-multiple"></i><span> Maps </span> <span class="badge badge-pill badge-danger float-right">2</span></a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("maps-google", "Maps")"> Google Map</a></li>
                        <li><a href="@Url.Action("maps-vector", "Maps")"> Vector Map</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-google-pages"></i><span> Pages </span> <span class="float-right"><i class="mdi mdi-chevron-right"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("pages-login", "Pages")">Login</a></li>
                        <li><a href="@Url.Action("pages-register", "Pages")">Register</a></li>
                        <li><a href="@Url.Action("pages-recoverpw", "Pages")">Recover Password</a></li>
                        <li><a href="@Url.Action("pages-lock-screen", "Pages")">Lock Screen</a></li>
                        <li><a href="@Url.Action("pages-blank", "Pages")">Blank Page</a></li>
                        <li><a href="@Url.Action("pages-404", "Pages")">Error 404</a></li>
                        <li><a href="@Url.Action("pages-500", "Pages")">Error 500</a></li>
                    </ul>
                </li>

            </ul>
        </div>
        <div class="clearfix"></div>
    </div> <!-- end sidebarinner -->
</div>

77Annex-MVC5_v1.0.0 22 08/Annex-MVC5_v1.0.0 22 08/Admin/Vertical/Views/Shared/_TopBar.cshtml
<div class="topbar">

    <nav class="navbar-custom">

        <ul class="list-inline float-right mb-0">
            <!-- language-->
            <li class="list-inline-item dropdown notification-list hide-phone">
                <a class="nav-link dropdown-toggle arrow-none waves-effect text-white" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="false" aria-expanded="false">
                    English <img src="~/assets/images/flags/us_flag.jpg" class="ml-2" height="16" alt="" />
                </a>
                <div class="dropdown-menu dropdown-menu-right language-switch">
                    <a class="dropdown-item" href="#"><img src="~/assets/images/flags/italy_flag.jpg" alt="" height="16" /><span> Italian </span></a>
                    <a class="dropdown-item" href="#"><img src="~/assets/images/flags/french_flag.jpg" alt="" height="16" /><span> French </span></a>
                    <a class="dropdown-item" href="#"><img src="~/assets/images/flags/spain_flag.jpg" alt="" height="16" /><span> Spanish </span></a>
                    <a class="dropdown-item" href="#"><img src="~/assets/images/flags/russia_flag.jpg" alt="" height="16" /><span> Russian </span></a>
                </div>
            </li>
            <li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none waves-effect" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <i class="ti-email noti-icon"></i>
                    <span class="badge badge-danger noti-icon-badge">5</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-menu-lg">
                    <!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5><span class="badge badge-danger float-right">745</span>Messages</h5>
                    </div>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon"><img src="~/assets/images/users/avatar-2.jpg" alt="user-img" class="img-fluid rounded-circle" /> </div>
                        <p class="notify-details"><b>Charles M. Jones</b><small class="text-muted">Dummy text of the printing and typesetting industry.</small></p>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon"><img src="~/assets/images/users/avatar-3.jpg" alt="user-img" class="img-fluid rounded-circle" /> </div>
                        <p class="notify-details"><b>Thomas J. Mimms</b><small class="text-muted">You have 87 unread messages</small></p>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon"><img src="~/assets/images/users/avatar-4.jpg" alt="user-img" class="img-fluid rounded-circle" /> </div>
                        <p class="notify-details"><b>Luis M. Konrad</b><small class="text-muted">It is a long established fact that a reader will</small></p>
                    </a>

                    <!-- All-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        View All
                    </a>

                </div>
            </li>

            <li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none waves-effect" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <i class="ti-bell noti-icon"></i>
                    <span class="badge badge-success noti-icon-badge">23</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-menu-lg">
                    <!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5><span class="badge badge-danger float-right">87</span>Notification</h5>
                    </div>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-primary"><i class="mdi mdi-cart-outline"></i></div>
                        <p class="notify-details"><b>Your order is placed</b><small class="text-muted">Dummy text of the printing and typesetting industry.</small></p>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-success"><i class="mdi mdi-message"></i></div>
                        <p class="notify-details"><b>New Message received</b><small class="text-muted">You have 87 unread messages</small></p>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-warning"><i class="mdi mdi-martini"></i></div>
                        <p class="notify-details"><b>Your item is shipped</b><small class="text-muted">It is a long established fact that a reader will</small></p>
                    </a>

                    <!-- All-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        View All
                    </a>

                </div>
            </li>

            <li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none waves-effect nav-user" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <img src="~/assets/images/users/avatar-1.jpg" alt="user" class="rounded-circle">
                </a>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                    <!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5>Welcome</h5>
                    </div>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-account-circle m-r-5 text-muted"></i> Profile</a>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-wallet m-r-5 text-muted"></i> My Wallet</a>
                    <a class="dropdown-item" href="#"><span class="badge badge-success float-right">5</span><i class="mdi mdi-settings m-r-5 text-muted"></i> Settings</a>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-lock-open-outline m-r-5 text-muted"></i> Lock screen</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-logout m-r-5 text-muted"></i> Logout</a>
                </div>
            </li>

        </ul>

        <ul class="list-inline menu-left mb-0">
            <li class="float-left">
                <button class="button-menu-mobile open-left waves-light waves-effect">
                    <i class="mdi mdi-menu"></i>
                </button>
            </li>
            <li class="hide-phone app-search">
                <form role="search" class="">
                    <input type="text" placeholder="Search..." class="form-control">
                    <a href=""><i class="fa fa-search"></i></a>
                </form>
            </li>
        </ul>

        <div class="clearfix"></div>

    </nav>

</div>